import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '../components/header/Header'
import TopCards from '../components/topcards/TopCards'
import BarChart from '../components/barchart/BarChart'
import ResentOrders from '../components/resentorders/ResentOrders'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main' >
        <Header />
        <TopCards />
        <div className="boxChart">
        <BarChart />
        <ResentOrders />
        </div>
      </main>
      <footer></footer>

    </>
  )
}
